models/Result.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "result".
 *
 * @property integer $season_id
 * @property integer $season_kriteria_id
 * @property integer $season_participant_id
 * @property integer $points
 *
 * @property SeasonKriteria $season
 */
class Result extends GenResult 
{
	 /**
     * @return \yii\db\ActiveQuery
     */
    public function getKriteria()
    {
        return $this->hasOne(Kriteria::className(), ['id' => 'season_kriteria_id']);
    }

    public function getPointResult()
    {
    	return $this->points * $this->kriteria->points_per_unit;
    }
}

models/Season.php
<?php

namespace app\models;

use Yii;

use yii\db\Query;

/**
 * This is the model class for table "season".
 *
 * @property integer $id
 * @property string $name
 * @property integer $isActive
 *
 * @property SeasonKriteria[] $seasonKriterias
 * @property Kriteria[] $idKriterias
 * @property SeasonParticipant[] $seasonParticipants
 * @property Unit[] $idUnits
 */
class Season extends GenSeason
{
	public $participant_ids = [];

	public $kriteria_ids = [];


	public function GetResults()
	{
		return Result::find()->where(['season_id' => $this->id])->with('kriteria')->all();
	}

	public static function GetCurrentSeason()
	{
		return Season::find()->where(['isActive' => 1])->orderBy(['id' => SORT_DESC])->limit(1)->one();
	}

	public function GetResultsPerGroup($orderBy = 'unit.code')
	{

		$query = new Query;

		return $query->select(['season_participant_id as unit_id', 'unit.short_name as short_name', 'kriteria.kriteria_group_id as kategorie', 'ROUND(SUM(points * kriteria.points_per_unit),2) as body'])
			->from('result')
			->where(['season_id'=>$this->id])
			->leftJoin('kriteria','kriteria.id = season_kriteria_id')
			->leftJoin('unit', 'unit.id = season_participant_id')
			->groupBy('kriteria.kriteria_group_id, season_participant_id')
			->orderBy($orderBy)
			->all();
	}

	public function GetOveralChartData()
	{
		$rawData = $this->resultsPerGroup;

        $dataPerUnit = [];

        foreach ($rawData as $row) {
            if (!array_key_exists($row['unit_id'], $dataPerUnit))
            {
                $dataPerUnit[$row['unit_id']] = [];
            }
            $dataPerUnit[$row['unit_id']][strval($row['kategorie'])] = doubleval($row['body']);
        }

        $data = [];
        foreach ($dataPerUnit as $unit_id => $row) {
        	$unit =  Unit::findOne($unit_id);
            $row['unit_name'] = $unit->name;
            $row['unit_code'] = $unit->code;
            $row['unit_short'] = $unit->short_name;
            $data[] = $row;
        }

        return $data;
	}
}

controllers/SeasonController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Result;
use app\models\Season;
use app\models\SeasonParticipant;
use app\models\SeasonKriteria;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

use yii\helpers\VarDumper;

/**
 * SeasonController implements the CRUD actions for Season model.
 */
class SeasonController extends BaseController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ] + parent::behaviors();
    }

    /**
     * Lists all Season models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Season::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Season model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Season model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Season();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Season model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $model->participant_ids = ArrayHelper::GetColumn(
                        $model->seasonParticipants,
                        'unit_id'
                    );

        $model->kriteria_ids = ArrayHelper::GetColumn(
                        $model->seasonKriterias,
                        'kriteria_id'
                    );

        if ($model->load(Yii::$app->request->post()))
        {
            $model->save();
            //Update Participants

            $old_participant_ids = $model->participant_ids;
            $new_participant_ids = Yii::$app->request->post()['Season']['participant_ids'];

            $to_create = array_diff($new_participant_ids, $old_participant_ids);

            foreach ($to_create as $newParticipantId) {
                $participant = new SeasonParticipant();
                $participant->unit_id = $newParticipantId;
                $participant->season_id = $model->id;
                $participant->save();
            }

            $to_delete = array_diff($old_participant_ids, $new_participant_ids);
            SeasonParticipant::deleteAll(['season_id' => $model->id, 'unit_id' => $to_delete]);

            $model->participant_ids = $new_participant_ids;

            //Update Kriteria

            $old_kriteria_ids = $model->kriteria_ids;
            $new_kriteria_ids = Yii::$app->request->post()['Season']['kriteria_ids'];

            $to_create = array_diff($new_kriteria_ids, $old_kriteria_ids);
            foreach ($to_create as $newKriteriaId) {
                $kriteria = new SeasonKriteria();
                $kriteria->kriteria_id = $newKriteriaId;
                $kriteria->season_id = $model->id;
                $kriteria->save();
            }

            $to_delete = array_diff($old_kriteria_ids, $new_kriteria_ids);
            SeasonKriteria::deleteAll(['season_id' => $model->id, 'kriteria_id' => $to_delete]);

            $model->kriteria_ids = $new_kriteria_ids;
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionResults($id)
    {

        if (array_key_exists('Result', Yii::$app->request->post()))
        {
            $results = Yii::$app->request->post()['Result'];

            foreach ($results as $krit_id => $results_by_kriteria) {
                foreach ($results_by_kriteria as $unit_id => $result) {

                    if ($model = Result::findOne(['season_id' => $id, 'season_kriteria_id' => $krit_id, 'season_participant_id' => $unit_id]))
                    {
                        $model->points = $result['points'];
                        $model->update();
                    }
                    else
                    {
                        $model = new Result(['season_id' => $id, 'season_kriteria_id' => $krit_id, 'season_participant_id' => $unit_id, 'points'=>$result['points']]);
                        $model->save();
                    }
                }
            }

            return $this->redirect(['view', 'id' => $id]);
        }

        $model = $this->findModel($id);

        $kriterias = $model->kriterias;
        $units = $model->units;



        $results = array();
        foreach ($kriterias as $krit) {
            $row = array();
            foreach ($units as $unit) {
                $row[$unit->id] = new Result(['points' => 0]);
            }
            $results[$krit->id] = $row;
        }



        $existingResults = $model->results;

        foreach ($existingResults as $exResult) {
            $results[$exResult->season_kriteria_id][$exResult->season_participant_id] = $exResult;
        }

        return $this->render('results', [
            'model' => $model, 'results'=>$results
        ]);
    }

    /**
     * Deletes an existing Season model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Season model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Season the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Season::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/season/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Season */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="season-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isActive')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/season/_kriteria.php
<?php
	use app\models\Kriteria;
	use yii\helpers\Html;
	use yii\widgets\ActiveForm;

	//Unit::ListStredisko();


	$items = [];

	foreach (Kriteria::find()->all() as $kriteria) {
		$items[$kriteria->id] = $kriteria->short_description;
	}

	echo $form->field($model, 'kriteria_ids')->checkBoxList($items);

	
?>

views/season/_tableResults.php
<?php

use app\models\Kriteria;

use yii\helpers\Html;
use yii\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;



    ?>
    <div style="border: solid 0px red; clear: both">

		<h2>Seznam všech kritérií</h2>

		<p class="normal">
		<table class="KHMS_table" border=1>
		<tr><!--<td></td>//--><td class="KHMS_table" style="text-align: right; width: 100px"><b>Termín vyhodnocení</b></td><td class="KHMS_table" style="text-align: left;"><b>Kritérium</b></td><td style="text-align: center; width: 50px"><b>Body</b></td><td style="text-align: center; width: 190px"><b>Skupina kritérií</b></td></tr>
		
		<?
        $kriteria = Kriteria::find()->OrderBy('termin')->all();
		foreach ($kriteria as $kriterium) {
			
			$termin_month=$kriterium->termin ? date_create($kriterium->termin)->format('m'):0;
		    if ($termin_month==12||$termin_month==1||$termin_month==2):
	    		$bg_color="#eef6ff";
	    	elseif ($termin_month==3||$termin_month==4||$termin_month==5):
	    		$bg_color="#efffe6";
	    	elseif ($termin_month==6||$termin_month==7||$termin_month==8):
	    		$bg_color="#feffea";
	    	elseif ($termin_month==9||$termin_month==10||$termin_month==11):
	    		$bg_color="#fff0f4";
	    	else:
	    		$bg_color="";			
	    	endif;	
			
			echo "<tr height=20><!--<td style=\"text-align: right;\">".$kriterium->id."</td>//-->
                    <td class=\"KHMS_table\" style=\"text-align: right; background: ".$bg_color."\">". ($kriterium->termin ? date_create($kriterium->termin)->format('j.m.') : "průběžně") ."</td>
                    <td class=\"KHMS_table\" style=\"text-align: left;\">".$kriterium->short_description."</td>
                    <td style=\"text-align: center\">".($kriterium->points_per_unit * $kriterium->basic_unit)."</td>
                    <td style=\"text-align: center\">".$kriterium->kriteriaGroup->name."</td></tr>";
		}

    	?>
    	</table>
    	<br>
    	</div>
    
    
    
    <h2>Kompletní tabulka bodů</h2>
    
    <table class="table table-header-rotated">
    <thead>
    <tr>

    	<th></th>

    <?php
    	foreach ($units as $unit) {
    ?>
    		<th class="rotate"><div><span><?= $unit->short_name ?></span></div></th>
    <?php
    	}
    ?>

    </tr>
    </thead>
	

	<tbody>
	<?php
    	foreach ($kriterias as $kriteria) {
    ?>
    	<tr>
    		<th class="row-header"><?= $kriteria->short_description ?></th>
    		<?php foreach ($units as $unit) {
                $result = $results[$kriteria->id][$unit->id];
    		?>
    		<td><?php echo $result->pointResult ?></td>
    		<?php } ?>
    	</tr>
    	<?php
    		}
    	?>
    	</tbody>
   
    </table>


</div>

views/season/_units.php
<?php
	use app\models\Unit;
	use yii\helpers\Html;
	use yii\widgets\ActiveForm;

	//Unit::ListStredisko();

	echo $form->field($model, 'participant_ids')->checkBoxList(Unit::ListStredisko());
?>

views/season/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Season */

$this->title = 'Create Season';
$this->params['breadcrumbs'][] = ['label' => 'Seasons', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="season-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/season/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Seasons';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="season-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Season', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'isActive',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/season/results.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Season */

$this->title = 'Výsledky: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Ročník', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Výsledky';

?>
<div class="season-update">

    <h1><?= Html::encode($this->title) ?></h1>

<?php
    	$form = ActiveForm::begin();
    ?>
    <table class="table table-header-rotated">
    <thead>
    <tr>

    	<th><?= Html::submitButton('Ulozit', ['class' => 'btn btn-primary']);?></th>

    <?php
    	foreach ($model->units as $unit) {
    ?>
    		<th class="rotate"><div><span><?= $unit->name ?></span></div></th>
    <?php
    	}
    ?>

    </tr>
    </thead>
	
    

	<tbody>
	<?php
    	foreach ($model->kriterias as $kriteria) {
    ?>
    	<tr>
    		<th class="row-header"><?= $kriteria->short_description ?></th>
    		<?php foreach ($model->units as $unit) {
    		?>
    		<td><?php echo $form->field($results[$kriteria->id][$unit->id], "[$kriteria->id][$unit->id]points")->label(false);?></td>
    		<?php } ?>
    	</tr>
    	<?php
    		}
    	?>

    	</tbody>
   
    </table>

    <?php
    	$form = ActiveForm::end();
    ?>

</div>

views/season/update.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Season */

$this->title = 'Úpravy ročníku ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Ročník', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Úpravy';
?>
<div class="season-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="season-form">
	    <?php $form = ActiveForm::begin(); ?>

	    <div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Vytvořit' : 'Upravit', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>

	    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'isActive')->checkbox() ?>
	<?php
	echo Tabs::widget([
	    'items' => [
	    	[
	        	'label' => 'Kritéria',
	        	'content' => $this->render('_kriteria', ['form'=>$form, 'model'=>$model]),
	        	'active' => true
	        ],
	        [
	            'label' => 'Jednotky',
	            'content' => $this->render('_units', ['form'=>$form, 'model'=>$model]),
	            
	        ],
    	],
    ]);
    ?>
    	    <?php ActiveForm::end(); ?>
	</div>
</div>

views/season/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Season */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Seasons', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="season-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Zadat výsledky', ['results', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Upravit', ['update', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?= Html::a('Smazat', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'isActive',
        ],
    ]) ?>

</div>