models/Unit.php
<?php

namespace app\models;


use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is helper class to filter queries based on a year (used in "via" for registrations)
 */
class RegistrationFilter
{
    public $year = null;

    public $units = null;

    public $cathegories = null;

    public function filterQuery($query)
    {
        $where = [];
        if ($this->year) $where['year'] = $this->year;
        if ($this->units) $where['unit_id'] = $this->units;
        if ($this->cathegories) $where['cathegory'] = $this->cathegories;
        return $query->where($where);
            
    }
}

/**
 * This is the model class for table "unit".
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $super_unit_id
 * @property string $type
 *
 * @property Unit $superUnit
 * @property Unit[] $units
 */
class Unit extends GenUnit
{
    public function getAllSubunitsIds()
    {
        $ids = [$this->id];

        $units = $this->units;
        foreach ($units as $unit)
        {
            $subIds = $unit->getAllSubunitsIds();
            $ids = array_merge($subIds, $ids);
        }
        return $ids;
    }

    public function getMembers($year)
    {
        $regFilter = new RegistrationFilter();
        $regFilter->year = $year;

        return $this->hasMany(Person::className(),
            ['id' => 'person_id'])->via('registrations', [$regFilter, 'filterQuery']);
    }

    public function getAllMembers($year, $cathegories = null)
    {
        $regFilter = new RegistrationFilter();
        $regFilter->year = $year;
        $regFilter->units = $this->allSubunitsIds;
        $regFilter->cathegories = $cathegories;

        return $this->hasMany(Person::className(),
            ['id' => 'person_id'])->via('allRegistrations', [$regFilter, 'filterQuery']);
    }

    public function getAllRegistrations()
    {
        $query =  Registration::find();
        $query->multiple = true;
        return $query;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKlubovna()
    {
        if ($this->klubovna_id)
        {
            return $this->hasOne(Klubovna::className(), ['id' => 'klubovna_id']);   
        } elseif ($this->super_unit_id)
        {
            return $this->superUnit->klubovna;
        }
        return null;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuperUnit()
    {
        return $this->hasOne(Unit::className(), ['id' => 'super_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnits()
    {
        return $this->hasMany(Unit::className(), ['super_unit_id' => 'id']);
    }

    public function getZakladnaByPohlavi()
    {
        $years = Registration::GetYears();
        $data = [];

        foreach ($years as $year)
        {
            $dataRow['year'] = $year;

            $result = ArrayHelper::map($this->getAllMembers($year)->select('count(*) as hc, sex')->groupBy('sex')->asArray()->all(),
                                    'sex','hc');
            
            $dataRow['male'] = array_key_exists('male', $result) ? $result['male'] : 0;
            $dataRow['female'] = array_key_exists('female', $result) ? $result['female'] : 0;

            $data[] = $dataRow;
        }

        return $data;
    }

    public function isParentOf($unit)
    {
        if ($this == $unit) return true;
        if (!$unit->super_unit_id) return false;

        return $this->isParentOf($unit->superUnit);
    }

    public static function GetSuperCathegory()
    {
        return [
            'Družina'=>'Oddíl',
            'Oddíl'=>'Středisko',
            'Středisko'=>'Okres',
            'Okres'=>''
        ];
    }

    public static function ContainsCathegory($units, $cathegory)
    {
        foreach ($units as $unit) {
            if ($unit->type == $cathegory) return true;
        }
        return false;
    }

    public static function ListStredisko()
    {
        $data = Unit::find()->select(['id', 'name'])->where(['type'=>'Středisko'])->all();
        return ArrayHelper::map($data, 'id', 'name');
    }

    public static function GetTypesArray()
    {
        return [ 'Oddíl' => 'Oddíl', 'Středisko' => 'Středisko', 'Družina' => 'Družina', 'Okres' => 'Okres', ];
    }

    public static function GetORJSumperk()
    {
        return Unit::findOne(84);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;

use app\models\Unit;
use app\models\Event;
use app\models\Ukoly;
use app\models\Season;
use app\models\FunkcePersonUnit;
use app\models\Document;

use yii\helpers\Json;
use \yii2fullcalendar\models\Event as CalEvent;

class SiteController extends BaseController
{
    public $freeAccessActions = ['index', 'about', 'orj','dokumenty','onas', 'kalendar','jsoncalendar','khms','khmsnavody','khmsstredisko'];


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ] + parent::behaviors();
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $model = $this->findUnitModel(84);

        $aktuality = Yii::$app->db->createCommand("(SELECT id,
                                                           'news' type,
                                                           valid_from date,
                                                           -1 as sign,
                                                           ABS(TO_DAYS(valid_from)-TO_DAYS(NOW())) as dist 
                                                        FROM news WHERE (TO_DAYS(valid_from)-TO_DAYS(NOW()))<=0)
                                                    UNION
                                                    (SELECT id,
                                                            'document' type,
                                                            valid_from date,
                                                            -1 sign,
                                                            ABS(TO_DAYS(created_at)-TO_DAYS(NOW())) dist
                                                        FROM document WHERE (TO_DAYS(created_at)-TO_DAYS(NOW()))<=0)
                                                    UNION
                                                    (SELECT id,
                                                            'ukoly' type,
                                                            termin date, 
                                                            1 sign,
                                                            ABS(TO_DAYS(termin)-TO_DAYS(NOW())) dist
                                                        FROM ukoly WHERE (TO_DAYS(termin)-TO_DAYS(NOW()))>=0)
                                                    UNION
                                                    (SELECT id,
                                                            'event' type,
                                                            start_date date,
                                                            1 sign,
                                                            ABS(TO_DAYS(start_date)-TO_DAYS(NOW())) dist
                                                        FROM event WHERE (TO_DAYS(start_date)-TO_DAYS(NOW()))>=0)
                                                    UNION 
                                                    /* info o vlozeni akce do DB */                                                                                                           
                                                    (SELECT id,
                                                            'event' type,
                                                            created_at date,
                                                            -1 sign,
                                                            ABS(TO_DAYS(created_at)-TO_DAYS(NOW())) dist
                                                        FROM event WHERE show_zalozeni_notification = 1
                                                        AND (TO_DAYS(created_at)-TO_DAYS(NOW()))<=0
                                                        AND (ABS(TO_DAYS(created_at)-TO_DAYS(NOW()))<ABS(TO_DAYS(prihlaseni_date)-TO_DAYS(NOW()))
                                                        	OR prihlaseni_date IS NULL)
                                                        AND (ABS(TO_DAYS(created_at)-TO_DAYS(NOW()))<ABS(TO_DAYS(start_date)-TO_DAYS(NOW()))
                                                        	OR start_date IS NULL))
                                                    UNION
                                                    /* info o terminu prihlaseni na akci */
                                                    (SELECT id,
                                                            'prihlaseni' type,
                                                            prihlaseni_date date,
                                                            1 sign,
                                                            ABS(TO_DAYS(prihlaseni_date)-TO_DAYS(NOW())) dist
                                                        FROM event WHERE (TO_DAYS(prihlaseni_date)-TO_DAYS(NOW()))>=0)
                                                    ORDER BY dist LIMIT 8")->queryAll();

        return $this->render('index',['model' => $model, 'resultChartData'=>Season::GetCurrentSeason()->overalChartData, 'aktuality'=>$aktuality]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        return $this->render('contact');
    }

    public function actionAbout()
    {
        $model = $this->findUnitModel(84);

        return $this->render('about', ['model' => $model]);
    }
    
    public function actionOnas()
    {
        $model = $this->findUnitModel(84);

        $strediska = Unit::Find()
    	//-> where(['type' => 'Středisko'])
    	//-> Where (['super_Unit_id' => 84])
    	-> Where (['like', 'Code', '715'])
    	-> orderBy('Code')
    	-> all();
        
        return $this->render('onas', ['model' => $model, 'strediska' => $strediska]);
    }
    
    public function actionDokumenty()
    {
        $model = $this->findUnitModel(84);
        
        $dokument = Document::Find()
        	//-> where(['id' => 3])
        	-> orderBy('valid_from DESC')
        	-> all();

        $zapisyDataProvider = new ActiveDataProvider([
            'query' => Document::find()->where(['type' => 'zapis'])->orderBy('id DESC')
        ]);
        
 
        return $this->render('dokumenty', ['model' => $model, 'dokument' => $dokument, 'zapisyDataProvider' => $zapisyDataProvider]);
    }
    
    public function actionOrj()
    {
	    $model = $this->findUnitModel(84);

        $clenoveRady = [];

        //Funkce Okresu
        $funkceOkres = FunkcePersonUnit::find()->where(['id_unit' => 84])->orderBy('order')->all();
	    foreach ($funkceOkres as $f) {
            if (!$f->funkce->isOrjMember) continue;
            if (array_key_exists($f->person->id, $clenoveRady))
            {
                $clenoveRady[$f->person->id]['funkce'][] = $f->funkce;
            }
            else
            {
                $clenoveRady[$f->person->id] = ['osoba' => $f->person, 'funkce' => [$f]];
            }
        }

        //Funkce v podrizenych jednotkach
        $funkceOstatni = FunkcePersonUnit::find()->where(['not', ['id_unit'=> 84]])->orderBy('order')->all();
        foreach ($funkceOstatni as $f) {
            if (!$f->funkce->isOrjMember || !$model->isParentOf($f->unit)) continue;

            if (array_key_exists($f->person->id, $clenoveRady))
            {
                $clenoveRady[$f->person->id]['funkce'][] = $f;
            }
            else
            {
                $clenoveRady[$f->person->id] = ['osoba' => $f->person, 'funkce' => [$f]];
            }
        }


        return $this->render('orj', ['model' => $model, 'clenoveRady' => $clenoveRady]);
    }

    public function actionKalendar()
    {
        return $this->render('kalendar');
    }

    
    public function actionKhms()
    {
        return $this->render('khms');
    }

    public function actionKhmsnavody()
    {
        return $this->render('khmsnavody');
    }
    
    public function actionKhmsstredisko($aktualni_stredisko = 9,$season=-1)
    {
        $rocnik = Season::findOne($season);
        if (!$rocnik)
        {
            $rocnik = Season::GetCurrentSeason();
        }

        return $this->render('khmsstredisko', ['rocnik'=> $rocnik, 'aktualni_stredisko' => $aktualni_stredisko]);
    }
    
    public function actionJsoncalendar($start=NULL,$end=NULL,$_=NULL)
    {
        $udalosti = Event::find()->where(['and',['>=','end_date', $start], ['<=', 'start_date', $end]])->all();

        $events = [];
        $idCounter = 0;
        foreach ($udalosti as $row) {
            $Event = new CalEvent();

views/site/_clenRady.php
<div class="col-sm-6 col-md-4">
<div class="thumbnail">
  <? if (File_Exists("images/lide/".$model['osoba']->id.".gif")): ?>
  <img src="images/lide/<?= $model['osoba']->id ?>.gif" class="portret">
  <? elseif (File_Exists("images/lide/".$model['osoba']->id.".jpg")): ?>
  <img src="images/lide/<?= $model['osoba']->id ?>.jpg" class="portret">
  <? endif; ?>
  <div class="caption">
    <h3><?= /*$model['osoba']->id.'. '.*/$model['osoba']->fullName ?></h3>
    <p>
    <ul class="list-unstyled">
    <?php foreach ($model['funkce'] as $f) { ?>
      <li><strong><?= $f->funkce->name ?></strong> <?= (($f->funkce->id)==1)?"(".$f->unit->name.")":""; ?></li>
    <?php } ?>
    </ul>
    </p>
  </div>
 </div>
 </div>

views/site/about.php
 <?php
/* @var $this yii\web\View */
$this->title = 'GISkaut';

use app\models\Unit;
use app\models\Registration;
use app\models\Person;
use app\models\Klubovna;
use app\widgets\GoogleCharts;
use app\widgets\GoogleMap;

use yii\helpers\Html;
?>

<div class="col-md-7">


      <div class="titulni_box" id="box_aktuality">
      <p class="box_nadpis">Aktuální dění</p>
      <div class="box_doplnkove_info">novinky, úkoly, pozvánky</div>
      <br>

      <?php

      $funkce_all = $model->funkcePersonUnits;

      foreach ($funkce_all as $funkce) {
        //echo $funkce->funkce->name . ' - ' . $funkce->person->name . ' ' . $funkce->person->surname . '<br>';
      }

 ?>
      <img src="images/sipka_main_page.png" class="sipka">
      </div>
      
      
      <br>
      <div class="titulni_box" id="box_onas">
      <p class="box_nadpis">Okresní rada</p>
      <div class="box_doplnkove_info">kontakt, lidé, poslání</div>
      <p>Junák - český skaut, okres Šumperk, z. s.<br>
      náměstí Jana Zajíce 11, 787 01 Šumperk<br>
      IČO: 603 41 921</p>
      <a href="?r=site/orj"><img src="images/sipka_main_page.png" class="sipka"></a>
      </div>
      <br>
</div>

<div class="col-md-5">
      <div class="titulni_box" id="box_statistiky">
      <p class="box_nadpis">Info o nás</p>
      <div class="box_doplnkove_info">kdo, kde, kontakty</div>
      <div class="mapa_main_page" style="margin-left:auto; margin-right: auto;  width: 80%">
   <?php 


GoogleMap::begin([
                        'id' => 'map-canvas',
                        'width' => '100%',
                        'height' => '250px'
                        ]) ?>
<script>
      function initialize() {
        var activeInfo;
        var heatmapData = [
        <?php 

        $members = Person::find()->all();
        $latSum = 0;
        $count = 0;
        $lngSum = 0; 
        foreach ($members as $member)
        {
          if (!$member->lat or !$member->lng or $member->lat < 40 or $member->lng < 10) continue;
          $count++;
          $latSum += $member->lat;
          $lngSum += $member->lng;
        ?>
            new google.maps.LatLng(<?= $member->lat ?> ,<?= $member->lng ?>),
            <?
        }
        ?>
        ];
        var mapCenter = new google.maps.LatLng( <?= $latSum / ($count ? $count : 1) ?>, <?= $lngSum / ($count ? $count : 1) ?>);
        var mapOptions = {
          //center: { lat: <?= $latSum / ($count ? $count : 1) ?>, lng: <?= $lngSum / ($count ? $count : 1) ?>},
          center: { lat: 49.933765, lng: 16.878613},
          zoom: 11,
          //maxZoom: 13,
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var heatmap = new google.maps.visualization.HeatmapLayer({
          data: heatmapData,
          //disipating: true.
          radius: 30,
        });
        heatmap.setMap(map);

        google.maps.event.addListener(map, 'zoom_changed', function() {
          var zoomLevel = map.getZoom();
          if (zoomLevel > 13)
          {
            heatmap.setMap(null);
          } else {
            heatmap.setMap(map);
          }
        });


        <?php
        $klubovny = Klubovna::find()->all();

        foreach($klubovny as $klubovna)
        {
            if (!$klubovna->lat or !$klubovna->lng or $klubovna->lat < 40 or $klubovna->lng < 10) continue;
            $units = $klubovna->GetAllUnits();
        ?>
            var marker<?= $klubovna->id ?> = new google.maps.Marker({
                position: new google.maps.LatLng(<?= $klubovna->lat ?> ,<?= $klubovna->lng ?>),
                map: map,
                title: '<?= $klubovna->name ?>',
                icon: '<?= Unit::ContainsCathegory($units, "Středisko") ? "images/stredisko.png" : "images/oddil.png" ?>',
            });

            var contentString = '<strong><?= $klubovna->name ?></strong>'
                              + '<ul>'
            <?php
            foreach ($units as $unit) {
              if ($unit->type == 'Družina') continue;
            ?>
                              + '<li><?= $unit->type ?> <?= Html::a($unit->name, ["chart/zakladna-vyvoj", "id"=>$unit->id]) ?></li>' 
            <?php
            }
            ?>
                              + '</ul>'

            var infoWindow<?= $klubovna->id ?> = new google.maps.InfoWindow({
               content: contentString,
            });

            google.maps.event.addListener(marker<?= $klubovna->id ?>, 'click', function() {
                if (activeInfo) activeInfo.close();
               infoWindow<?= $klubovna->id ?>.open(map,marker<?= $klubovna->id ?>);
               activeInfo = infoWindow<?= $klubovna->id ?>;
            });
        <?
        }
        
        ?>

      }
      google.maps.event.addDomListener(window, 'load', initialize);
</script>
<?php GoogleMap::end() ?>
    </div>
    <img src="images/sipka_main_page.png" class="sipka">
      </div>
      
      
      <br>
      <div class="titulni_box" id="box_khms">
      <p class="box_nadpis">Statistiky</p>
      <div class="box_doplnkove_info">grafy, čísla, tabulky</div>
      <br>
      <?= $this->render('/chart/_zakladna_pohlavi', ['data'=>$model->zakladnaByPohlavi]); ?>
      <img src="images/sipka_main_page.png" class="sipka">
      </div>
      
      
      <br>
      <div class="titulni_box" id="box_orj">
      <p class="box_nadpis">Kritéria hodnocení a motivace středisek</p>
      <br>
      <img src="images/sipka_main_page.png" class="sipka">
      </div>

</div>

views/site/contact.php
<?php 

    use app\assets\D3Asset;
    use app\models\Unit;

    use yii\bootstrap\Modal;

    D3Asset::register($this);

    $dataset = [
        'title' => 'ORJ',
        'subUnits' => []
    ];


    $strediska = Unit::find()->where(['type'=>'Středisko'])->orWhere(['type'=>'Okres'])->andWhere(['not', ['id'=>[2,85]]])->OrderBy('Code')->all();

    foreach ($strediska as $stredisko)
    {
        $s = [
            'title' => $stredisko->name,
            'subUnits' => []
        ];

        foreach ($stredisko->units as $oddil)
        {
            $s['subUnits'][] = ['title' => $oddil->name];
         //   echo Html::a($oddil->name, [$action, 'id' => $oddil->id], ['class' => 'list-group-item list-group-item-info '. 
          //                                      ($activeOddilId== $oddil->id ? 'active' : '')]);
        }

        $dataset['subUnits'][] = $s;
    }

  

?>
<br/><br/>
<?php

Modal::begin([
    'header' => '<h2>Hello world</h2>',
    'toggleButton' => [
        'tag'   => 'a',
        'label' => 't',
        //'href'  => '',
        ],
    ]);

    echo 'Say hello...';

    Modal::end();
?>

<svg id="graph" viewBox="0 0 960 500" preserveAspectRatio="xMidYMid">

<script>
var dataset =  <?php echo json_encode($dataset); ?>;

var width = 960,
    height = 500;

var x = d3.scale.linear()
    .range([0, width]);

var y = d3.scale.linear()
    .range([0, height]);

var color = d3.scale.category20c();

var partition = d3.layout.partition()
    .children(function(d) { return d['subUnits']; })
    .value(function(d) { return 1; });

var svg = d3.select("svg");

var data = partition(dataset);

var rect = svg.selectAll("rect").data(data).enter()
 .append("svg:rect")
 .attr("x", function(d) { return x(d.x); })
      .attr("y", function(d) { return y(d.y); })
      .attr("width", function(d) { return x(d.dx); })
      .attr("height", function(d) { return y(d.dy); })
      .attr("fill", function(d) { return color(d.children ? d.title : d.parent.title); })
 
 .style("cursor", "pointer")
 .on("click", clicked);

var fo = svg.selectAll("foreignObject").data(data).enter()
 .append("svg:foreignObject")
 .attr("x", function(d) { return x(d.x); })
      .attr("y", function(d) { return y(d.y); })
      .attr("width", function(d) { return x(d.dx); })
      .attr("height", function(d) { return y(d.dy); })
      
 .style("cursor", "pointer")
 .text(function(d) { return d.title })
 .on("click", clicked);


function clicked(d) {
  x.domain([d.x, d.x + d.dx]);
  y.domain([d.y, 1]).range([d.y ? 20 : 0, height]);

  rect.transition()
      .duration(750)
      .attr("x", function(d) { return x(d.x); })
      .attr("y", function(d) { return y(d.y); })
      .attr("width", function(d) { return x(d.x + d.dx) - x(d.x); })
      .attr("height", function(d) { return y(d.y + d.dy) - y(d.y); });

  fo.transition()
      .duration(750)
      .attr("x", function(d) { return x(d.x); })
      .attr("y", function(d) { return y(d.y); })
      .attr("width", function(d) { return x(d.x + d.dx) - x(d.x); })
      .attr("height", function(d) { return y(d.y + d.dy) - y(d.y); });
}
</script>

views/site/dokumenty.php
<?php
/* @var $this yii\web\View */
$this->title = 'GISkaut';

use app\models\Unit;
use app\models\Registration;
use app\models\Person;
use app\models\Klubovna;
use app\widgets\GoogleCharts;
use app\widgets\GoogleMap;

use yii\grid\GridView;

use yii\helpers\Html;
use yii\widgets\ListView;

use app\models\FunkcePersonUnit;
use yii\data\ArrayDataProvider;
use app\models\Document;


?>
<h1>Dokumenty</h1>
<h2>Zápisy z rad</h2>

<!--

<?= GridView::widget([
        'dataProvider' => $zapisyDataProvider,
        'columns' => [
            'title',

            'created_at',
            [
                'value'=> function($data) {
                    return '<a href="files/'.$data->file.'" target="_blank"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></a>';
                },
                'format' => 'html'
            ],
        ],
    ]); ?>
//-->
<p><div id="w0" class="row">


      <?php
      $recent_year=0;
      foreach ($dokument as $d) {
	      if ($d->type=="zapis") {
		      if (Substr($d->file,strlen($d->file)-4,4)==".pdf"):
		      	$iconm="iconm_pdf.png";
		      else:
		      	$iconm="iconm_file.png";
		      endif;  	
		   	
		     
		      echo ($recent_year==substr($d->valid_from,0,4))?'':(($recent_year==0)?'':'</div></div>').'<div class="col-sm-6 col-md-4"><div class="box_zapisy"><div class="rok_dokumenty"><strong>'.substr($d->valid_from,0,4).'</strong></div>';
		      echo '<a href="files/'.$d->file.'" target="_blank"><img src="images/'.$iconm.'">&nbsp;'.$d->title.'</a><br>';
		      $recent_year=substr($d->valid_from,0,4);
	      }
      }

?>
</div></div>
</div>
</p>
<h2>Vyhlášky a řády</h2>
<p>
<?
      foreach ($dokument as $d) {
	      if ($d->type=="vyhlaska") {
		  	echo '<a href="files/'.$d->file.'" target="_blank"><img src="images/'.$iconm.'">&nbsp;'.$d->title.'</a><br>';
 
	      }
      }

?>
</p>
<h2>Výroční zprávy</h2>
<p>
<?
      foreach ($dokument as $d) {
	      if ($d->type=="vz") {
		  	echo '<a href="files/'.$d->file.'" target="_blank"><img src="images/'.$iconm.'">&nbsp;'.$d->title.'</a><br>';
 
	      }
      }

?>
</p>
<h2>Ostatní</h2>
<p>
<?
      foreach ($dokument as $d) {
	      if ($d->type=="jine") {
		  	echo '<a href="files/'.$d->file.'" target="_blank"><img src="images/'.$iconm.'">&nbsp;'.$d->title.'</a><br>';
 
	      }
      }

?>
</p>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/kalendar.php
<?
use yii\helpers\Html;
?>
<div class="col-md-1">
</div>
<div class="col-md-8">
<?php
	use yii\helpers\Url;

  	echo \yii2fullcalendar\yii2fullcalendar::widget(array(
      //'events'=> $events,
      'ajaxEvents' => Url::to(['jsoncalendar']),
      'options'=> [
      	'lang' => 'cs'
      ],
  	));
?>
</div>

<div class="col-md-3">
<h2>Pořádané akce</h2>
<p><? echo Html::a("Rádcovský kurz ŠRÁKY <span class='glyphicon glyphicon-new-window' aria-hidden='true'></span>", "http://sraky.wakan.cz",['target' => '_blank']); ?></p>
<p><? echo Html::a("Víkendový kurz ŠUMIK <span class='glyphicon glyphicon-new-window' aria-hidden='true'></span>", "http://orjspk.skauting.cz/sumik2016",['target' => '_blank']); ?></p>
<h2>Fotoarchiv</h2>
<? echo Html::a("FB fotoarchiv <span class='glyphicon glyphicon-new-window' aria-hidden='true'></span>", "https://www.facebook.com/orjspk/photos_stream?tab=photos_albums",['target' => '_blank']); ?>
</div>

views/site/khms.php
<?php
/* @var $this yii\web\View */
$this->title = 'KHMS';

use app\models\Kriteria;

?>
<h1>Kritéria hodnocení a motivace středisek</h1>

<div style="border: solid 0px red; clear: both">

		<h2>Seznam všech kritérií</h2>
		<br>
		<p class="normal">
		<table class="KHMS_table" border=1>
		<tr><!--<td></td>//--><td style="text-align: right; width: 100px"><b>Termín vyhodnocení</b></td><td style="text-align: left;"><b>Kritérium</b></td><td style="text-align: center; width: 50px"><b>Body</b></td><td style="text-align: center; width: 190px"><b>Skupina kritérií</b></td></tr>
		
		<?
        $kriteria = Kriteria::find()->OrderBy('termin')->all();
		foreach ($kriteria as $kriterium) {
			
			$termin_month=$kriterium->termin ? date_create($kriterium->termin)->format('m'):0;
		    if ($termin_month==12||$termin_month==1||$termin_month==2):
	    		$bg_color="#eef6ff";
	    	elseif ($termin_month==3||$termin_month==4||$termin_month==5):
	    		$bg_color="#efffe6";
	    	elseif ($termin_month==6||$termin_month==7||$termin_month==8):
	    		$bg_color="#feffea";
	    	elseif ($termin_month==9||$termin_month==10||$termin_month==11):
	    		$bg_color="#fff0f4";
	    	else:
	    		$bg_color="";			
	    	endif;	
			
			echo "<tr height=20><!--<td style=\"text-align: right;\">".$kriterium->id."</td>//-->
                    <td style=\"text-align: right; background: ".$bg_color."\">". ($kriterium->termin ? date_create($kriterium->termin)->format('j.m.') : "průběžně") ."</td>
                    <td style=\"text-align: left;\">".$kriterium->short_description."</td>
                    <td style=\"text-align: center\">".($kriterium->points_per_unit * $kriterium->basic_unit)."</td>
                    <td style=\"text-align: center\">".$kriterium->kriteriaGroup->name."</td></tr>";
		}

    	?>
    	</table>
    	<br>
    	</div>